@webapiwc_HostAddress = http://localhost:5249
@userId = 38f826e8-a1c2-4844-a71f-aa19e7a7827f
@todoId = 11a0177d-acbf-45e8-a172-5b2093e18494


### get a todo by id
GET {{webapiwc_HostAddress}}/api/todo/{{todoId}}

### get all todos
GET {{webapiwc_HostAddress}}/api/todo

### create a todo
POST {{webapiwc_HostAddress}}/api/todo


### update a todo
PUT {{webapiwc_HostAddress}}/api/todo/{{todoId}}

### delete a todo
DELETE {{webapiwc_HostAddress}}/api/todo/{{todoId}}